### ISSUE TITLE
function dosen't return, outputs

### ISSUE THREAD

**Issue by smedsrud** [EJTH/SLinkedIn#3]
in SimpleLinkedIn.class line 276 the function parse_str is not returning value, needs second parameter to output array:  $query = parse_str($urlInfo['query']); should be  parse_str($urlInfo['query'], $query);

**Comment by magicodeuk** [comment]
Yes, this line of code is wrong. Please fix it. The library is useless otherwise!

**Comment by EJTH** [comment]
It has been fixed. I apoligize for the long wait.

**Comment by magicodeuk** [comment]
Great, thanks! :)
